---
title: "Main"
author: "willy"
date: "2024-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rstan)
library(rstanarm)
library(coda)
library(mvtnorm)
library(ggplot2)
library(bayesplot)
library(loo)
library(tidytext)
library(tidyverse)
library(textdata)
source("willy.R")
source("hugo.R")
set.seed(42)
```

## Importation

```{r}
TARGET_FEATURE = "percenttp"

RawData = ImportData("Q14_survey_for_dataverse.csv")
```


```{r}
#Data <- remove_columns(RawData, c("firstthought", "recent", "tpfeel", "biggest", "paystub", "depend", "glad", "upset", "benefit", "wastethink","eitcexp", "eitcthink"))

#Data <- RemoveNA(Data)

Data <- ReplaceNaWithValue(RawData, c("partyid"), 9)
Data <- ReplaceNaWithValue(Data, c("educ"), 7)
Data <- ReplaceNaWithValue(Data, c("wagesal"), 0)
Data <- ReplaceNaWithValue(Data, c("paystub"), 0)
Data <- ReplaceNaWithValue(Data, c("eitcself"), 0)
Data <- ReplaceNaWithValue(Data, c("eitcexp"), 0)
Data <- ReplaceNaWithValue(Data, c("eitcother"), 0)
Data <- ReplaceNaWithValue(Data, c("labforce"), 10)
Data <- ReplaceNaWithValue(Data, c("polideo"), 8)
Data <- ReplaceNaWithValue(Data, c("polinffreq"), 5)
Data <- ReplaceNaWithValue(Data, c("regvote"), 3)
Data <- ReplaceNaWithValue(Data, c("voted"), 3)
Data <- ReplaceNaWithValue(Data, c("discusspol"), 5)
Data <- ReplaceNaWithValue(Data, c("poleffic"), 6)
Data <- ReplaceNaWithValue(Data, c("polvol"), 5)
Data <- ReplaceNaWithValue(Data, c("raceeth"), 7)
Data <- ReplaceNaWithValue(Data, c("hhinc"), 20)

#Data <- ReplaceNaWithMean(Data, c("child", "wastecents"))
Data <- sentiment_columns(Data, c("firstthought", "tpfeel", "wastethink", "recent"))

Data <- CleanData(Data)

fake_check = generate_fake_data(Data)
fake_data = fake_check$fake_data
coef_fake = fake_check$coef

columns_to_exclude <- c("percenttp", "wastecents", "feelfedgov_1", "weightvec")
columns_to_convert <- setdiff(names(Data), columns_to_exclude)
Data[columns_to_convert] <- lapply(Data[columns_to_convert], as.factor)

GetDatasetInformation(Data)
```



```{r}
rstanarm_normalprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = normal(location = 0), prior_intercept = normal(location = 0))

rstanarm_normalprior_model <- BayesianLinearRegressionRstanarm(fake_data, TARGET_FEATURE, prior = normal(location = 0), prior_intercept = normal(location = 0))
```

```{r}
rstanarm_productnormalprior_model <- BayesianLinearRegressionRstanarm(fake_data, TARGET_FEATURE, prior = product_normal(df = 2, location = 0, scale = 1), prior_intercept = normal(location = 0))
```



Linear 

```{r}
rstanarm_normalprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = normal(location = 0), prior_intercept = normal(location = 0))

rstanarm_productnormalprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = product_normal(df = 2, location = 0, scale = 1), prior_intercept = normal(location = 0))

rstanarm_studentprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = student_t(df = 1, location = 0), prior_intercept = normal(location = 0))

rstanarm_cauchyprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = cauchy(location = 0), prior_intercept = normal(location = 0))

rstanarm_laplaceprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = laplace(location = 0), prior_intercept = normal(location = 0))

rstanarm_hsprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = hs(df = 1, global_df = 1, global_scale = 0.01, slab_df = 4, slab_scale = 2.5), prior_intercept = normal(location = 0))

rstanarm_lassoprior_model <- BayesianLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = lasso(df = 1, location = 0), prior_intercept = normal(location = 0))

```

Non Linear

```{r}
rstanarm_normalprior_nl_model <- BayesianNonLinearRegressionRstanarm(Data, TARGET_FEATURE, prior = normal(location = 0), prior_intercept = normal(location = 0), iter = 200, chain = 4)
```

## EVALUATION

### Rstanarm

Non Linear

```{r}
EvaluateBayesianRstanarmModel(rstanarm_normalprior_nl_model, Data, TARGET_FEATURE)
```

```{r}
BayesianMSERstanarm(rstanarm_productnormalprior_nl_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_studentprior_nl_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_cauchyprior_nl_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_laplaceprior_nl_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_hsprior_nl_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_lassoprior_nl_model, Data, TARGET_FEATURE)
```

Linear

```{r}
EvaluateBayesianRstanarmModel(rstanarm_normalprior_model, Data, TARGET_FEATURE)
```

```{r}
BayesianMSERstanarm(rstanarm_productnormalprior_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_studentprior_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_cauchyprior_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_laplaceprior_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_hsprior_model, Data, TARGET_FEATURE)
BayesianMSERstanarm(rstanarm_lassoprior_model, Data, TARGET_FEATURE)
```

### Rstan

```{r}
EvaluateBayesianRstanModel(normal_rstan_model, Data, TARGET_FEATURE)
```

```{r}
EvaluateBayesianRstanModel(student_rstan_model, Data, TARGET_FEATURE)
```

